using System.Security.Cryptography;

namespace PS5Craft.Services;

public sealed record AmprStatus(bool EbootImportsAmpr, bool ModulePresent, string? PresentVersion, string? PresentSha256)
{
    /// <summary>The game calls libSceAmpr but the folder has no emulator module (it is stripped when an FPKG is built).</summary>
    public bool NeedsModule => EbootImportsAmpr && !ModulePresent;
}

public sealed record AmprBuild(string Version, string Sha256, string Label)
{
    public string RelativeModulePath => Path.Combine("tools", "ampr_emu", Version, AmprEmulator.ModuleName);
}

/// <summary>
/// AMPR userland emulator (drakmor/ampr_emu, GPL-3.0) for folder/image launches. Package builders drop
/// <c>fakelib/libSceAmpr.sprx</c>, so a folder extracted from an FPKG lacks it. Bundled modules are unmodified
/// upstream release builds; different titles may need different versions. <c>ampr_emu.index</c> is generated by
/// MkPFS (or by the module at runtime).
/// </summary>
public static class AmprEmulator
{
    public const string ModuleName = "libSceAmpr.sprx";
    public const string FakeLibFolder = "fakelib";
    public const string IndexName = "ampr_emu.index";
    public const string SourceUrl = "https://github.com/drakmor/ampr_emu";
    public const string DefaultVersion = "0.3.6.6";

    /// <summary>Pinned unmodified upstream release builds shipped under tools/ampr_emu/&lt;version&gt;/.</summary>
    public static readonly IReadOnlyList<AmprBuild> KnownBuilds =
    [
        new("0.3.6.6", "362c84e31e3a06a42f50fe4d6ea124d15e73f77c901470f90823935d7f36ca76", "0.3.6.6 (часто для BP / старых дампов)"),
        new("0.4.2.1", "69e6c4d5e4f5fb83c9e01815db5861c4c75734acbf4595cafa50d4c218116d1a", "0.4.2.1 (последний release)")
    ];

    private static ReadOnlySpan<byte> ImportMarker => "libSceAmpr"u8;

    /// <summary>The dynlib string table sits right after the ELF headers; no need to read the whole executable.</summary>
    private const long MaxEbootScanBytes = 64L * 1024 * 1024;

    private const int ScanChunk = 1 << 20;

    public static string ModuleRelativePath => FakeLibFolder + "/" + ModuleName;

    public static AmprBuild? FindBuild(string? version) =>
        KnownBuilds.FirstOrDefault(b => b.Version.Equals(version, StringComparison.OrdinalIgnoreCase));

    public static AmprBuild? FindBuildBySha256(string sha256) =>
        KnownBuilds.FirstOrDefault(b => b.Sha256.Equals(sha256, StringComparison.OrdinalIgnoreCase));

    public static AmprStatus Inspect(string gameRoot, CancellationToken cancellationToken = default)
    {
        var modulePath = Path.Combine(gameRoot, FakeLibFolder, ModuleName);
        string? presentVersion = null;
        string? presentSha = null;
        var module = File.Exists(modulePath);
        if (module)
        {
            presentSha = ComputeSha256(modulePath);
            presentVersion = FindBuildBySha256(presentSha)?.Version ?? "unknown";
        }

        var eboot = Path.Combine(gameRoot, "eboot.bin");
        var imports = false;
        if (File.Exists(eboot))
        {
            using var stream = File.OpenRead(eboot);
            imports = ContainsImport(stream, cancellationToken);
        }

        return new AmprStatus(imports, module, presentVersion, presentSha);
    }

    public static bool ContainsImport(Stream stream, CancellationToken cancellationToken = default)
    {
        var marker = ImportMarker;
        var overlap = marker.Length - 1;
        var buffer = new byte[ScanChunk + overlap];
        var carried = 0;
        long scanned = 0;

        while (scanned < MaxEbootScanBytes)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var read = stream.Read(buffer, carried, ScanChunk);
            if (read <= 0)
            {
                break;
            }

            var available = carried + read;
            if (buffer.AsSpan(0, available).IndexOf(marker) >= 0)
            {
                return true;
            }

            scanned += read;
            carried = Math.Min(overlap, available);
            buffer.AsSpan(available - carried, carried).CopyTo(buffer);
        }

        return false;
    }

    public static IReadOnlyList<AmprBuild> ListAvailableBuilds(string? appBase = null)
    {
        appBase ??= AppContext.BaseDirectory;
        return KnownBuilds.Where(b => FindBundledModule(b.Version, appBase) is not null).ToList();
    }

    public static string? FindBundledModule(string version, string? appBase = null)
    {
        appBase ??= AppContext.BaseDirectory;
        var build = FindBuild(version);
        if (build is null)
        {
            return null;
        }

        string[] candidates =
        [
            Path.Combine(appBase, "tools", "ampr_emu", build.Version, ModuleName),
            Path.GetFullPath(Path.Combine(appBase, "..", "..", "..", "..", "..", "tools", "ampr_emu", build.Version, ModuleName)),
            // Legacy flat layout (single file) only for the default/latest known hashes.
            Path.Combine(appBase, "tools", "ampr_emu", ModuleName),
            Path.GetFullPath(Path.Combine(appBase, "..", "..", "..", "..", "..", "tools", "ampr_emu", ModuleName))
        ];

        foreach (var path in candidates)
        {
            if (!File.Exists(path))
            {
                continue;
            }

            var hash = ComputeSha256(path);
            if (hash.Equals(build.Sha256, StringComparison.OrdinalIgnoreCase))
            {
                return path;
            }
        }

        // Prefer the versioned folder even when hash check already filtered; return first existing versioned path.
        var versioned = candidates.Take(2).FirstOrDefault(File.Exists);
        return versioned;
    }

    /// <summary>
    /// Copies a bundled module to <c>&lt;root&gt;/fakelib/libSceAmpr.sprx</c>.
    /// Refuses a file whose hash differs from the pinned release. When <paramref name="overwrite"/> is false,
    /// refuses to replace an existing module.
    /// </summary>
    public static string Restore(string gameRoot, string bundledModulePath, AmprBuild build, bool overwrite = false)
    {
        var hash = ComputeSha256(bundledModulePath);
        if (!hash.Equals(build.Sha256, StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException(
                $"{bundledModulePath}: SHA-256 {hash} does not match ampr_emu {build.Version} ({build.Sha256}).");
        }

        var fakelib = Path.Combine(gameRoot, FakeLibFolder);
        var target = Path.Combine(fakelib, ModuleName);
        if (File.Exists(target) && !overwrite)
        {
            throw new IOException($"{target} already exists.");
        }

        Directory.CreateDirectory(fakelib);
        File.Copy(bundledModulePath, target, overwrite: overwrite);
        File.SetLastWriteTimeUtc(target, DateTime.UtcNow);

        // Index is tied to the module/app0 set; force MkPFS to regenerate after a version swap.
        var index = Path.Combine(gameRoot, IndexName);
        if (overwrite && File.Exists(index))
        {
            File.Delete(index);
        }

        return target;
    }

    public static string ComputeSha256(string path)
    {
        using var stream = File.OpenRead(path);
        return Convert.ToHexStringLower(SHA256.HashData(stream));
    }
}
