<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>PS5Craft.ViewModels</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PS5Craft.Core\PS5Craft.Core.csproj" />
    <ProjectReference Include="..\PS5Craft.Services\PS5Craft.Services.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>
</Project>
